if(EXISTS "/home/wwj/HXD/cpp/build_cuda/tests/test_cuda_irs_commit[1]_tests.cmake")
  include("/home/wwj/HXD/cpp/build_cuda/tests/test_cuda_irs_commit[1]_tests.cmake")
else()
  add_test(test_cuda_irs_commit_NOT_BUILT test_cuda_irs_commit_NOT_BUILT)
endif()
