add_test([=[CudaRsEncode.MatchesCpuForInterleavedEncode]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_cuda_rs_encode [==[--gtest_filter=CudaRsEncode.MatchesCpuForInterleavedEncode]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CudaRsEncode.MatchesCpuForInterleavedEncode]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CudaRsEncode.EmptyInputMatchesCpu]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_cuda_rs_encode [==[--gtest_filter=CudaRsEncode.EmptyInputMatchesCpu]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CudaRsEncode.EmptyInputMatchesCpu]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CudaRsEncode.Ext3MatchesCpuForInterleavedEncode]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_cuda_rs_encode [==[--gtest_filter=CudaRsEncode.Ext3MatchesCpuForInterleavedEncode]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CudaRsEncode.Ext3MatchesCpuForInterleavedEncode]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_cuda_rs_encode_TESTS CudaRsEncode.MatchesCpuForInterleavedEncode CudaRsEncode.EmptyInputMatchesCpu CudaRsEncode.Ext3MatchesCpuForInterleavedEncode)
