if(EXISTS "C:/Users/dong77/Desktop/WhirPlonk/cpp/build_cuda/tests/test_protocols[1]_tests.cmake")
  include("C:/Users/dong77/Desktop/WhirPlonk/cpp/build_cuda/tests/test_protocols[1]_tests.cmake")
else()
  add_test(test_protocols_NOT_BUILT test_protocols_NOT_BUILT)
endif()
