if(EXISTS "/home/wwj/HXD/cpp/build_cuda/tests/test_protocols[1]_tests.cmake")
  include("/home/wwj/HXD/cpp/build_cuda/tests/test_protocols[1]_tests.cmake")
else()
  add_test(test_protocols_NOT_BUILT test_protocols_NOT_BUILT)
endif()
