add_test([=[NttGenerator.ReturnsRootForValidSize]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=NttGenerator.ReturnsRootForValidSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NttGenerator.ReturnsRootForValidSize]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NttGenerator.ReturnsNulloptForInvalidSize]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=NttGenerator.ReturnsNulloptForInvalidSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NttGenerator.ReturnsNulloptForInvalidSize]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NttGenerator.SizeOneReturnsOne]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=NttGenerator.SizeOneReturnsOne]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NttGenerator.SizeOneReturnsOne]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[InterleavedRsEncode.BasicEncoding]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=InterleavedRsEncode.BasicEncoding]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[InterleavedRsEncode.BasicEncoding]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChallengeIndices.EmptyCount]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ChallengeIndices.EmptyCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChallengeIndices.EmptyCount]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChallengeIndices.SingleLeaf]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ChallengeIndices.SingleLeaf]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChallengeIndices.SingleLeaf]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChallengeIndices.DedupWorks]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ChallengeIndices.DedupWorks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChallengeIndices.DedupWorks]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ChallengeIndices.NoDedupKeepsAll]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ChallengeIndices.NoDedupKeepsAll]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ChallengeIndices.NoDedupKeepsAll]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.BasicTree]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=MerkleTree.BasicTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.BasicTree]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ProofOfWork.ZeroDifficulty]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ProofOfWork.ZeroDifficulty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ProofOfWork.ZeroDifficulty]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ProofOfWork.FindNonceZeroDifficulty]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ProofOfWork.FindNonceZeroDifficulty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ProofOfWork.FindNonceZeroDifficulty]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ProofOfWork.ThresholdRoundTrip]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ProofOfWork.ThresholdRoundTrip]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ProofOfWork.ThresholdRoundTrip]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SumcheckIntegration.ProveVerifyCycle]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=SumcheckIntegration.ProveVerifyCycle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SumcheckIntegration.ProveVerifyCycle]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SumcheckIntegration.EmptySumcheck]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=SumcheckIntegration.EmptySumcheck]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SumcheckIntegration.EmptySumcheck]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TranscriptIntegration.RoundTrip]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=TranscriptIntegration.RoundTrip]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TranscriptIntegration.RoundTrip]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GeometricChallenge.ProducesGeometricSequence]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=GeometricChallenge.ProducesGeometricSequence]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GeometricChallenge.ProducesGeometricSequence]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IrsCommitIntegration.CommitAndVerify]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=IrsCommitIntegration.CommitAndVerify]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IrsCommitIntegration.CommitAndVerify]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EndToEnd.MiniSumcheckToIrsCommit]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=EndToEnd.MiniSumcheckToIrsCommit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EndToEnd.MiniSumcheckToIrsCommit]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[WhirIntegration.FullProveVerifyCycle]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=WhirIntegration.FullProveVerifyCycle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[WhirIntegration.FullProveVerifyCycle]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ZkWhirIntegration.FullProveVerifyCycle]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_protocols [==[--gtest_filter=ZkWhirIntegration.FullProveVerifyCycle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZkWhirIntegration.FullProveVerifyCycle]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_protocols_TESTS NttGenerator.ReturnsRootForValidSize NttGenerator.ReturnsNulloptForInvalidSize NttGenerator.SizeOneReturnsOne InterleavedRsEncode.BasicEncoding ChallengeIndices.EmptyCount ChallengeIndices.SingleLeaf ChallengeIndices.DedupWorks ChallengeIndices.NoDedupKeepsAll MerkleTree.BasicTree ProofOfWork.ZeroDifficulty ProofOfWork.FindNonceZeroDifficulty ProofOfWork.ThresholdRoundTrip SumcheckIntegration.ProveVerifyCycle SumcheckIntegration.EmptySumcheck TranscriptIntegration.RoundTrip GeometricChallenge.ProducesGeometricSequence IrsCommitIntegration.CommitAndVerify EndToEnd.MiniSumcheckToIrsCommit WhirIntegration.FullProveVerifyCycle ZkWhirIntegration.FullProveVerifyCycle)
