add_test([=[CudaMerklePath.MatchesCpuOpenPathHints]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_cuda_merkle_path [==[--gtest_filter=CudaMerklePath.MatchesCpuOpenPathHints]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CudaMerklePath.MatchesCpuOpenPathHints]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CudaMerklePath.TranscriptOpenVerifyLargeTree]=]  /home/wwj/HXD/cpp/build_cuda/tests/test_cuda_merkle_path [==[--gtest_filter=CudaMerklePath.TranscriptOpenVerifyLargeTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CudaMerklePath.TranscriptOpenVerifyLargeTree]=]  PROPERTIES WORKING_DIRECTORY /home/wwj/HXD/cpp/build_cuda/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_cuda_merkle_path_TESTS CudaMerklePath.MatchesCpuOpenPathHints CudaMerklePath.TranscriptOpenVerifyLargeTree)
