if(EXISTS "C:/Users/dong77/Desktop/WhirPlonk/cpp/build_cuda/tests/test_cuda_merkle_path[1]_tests.cmake")
  include("C:/Users/dong77/Desktop/WhirPlonk/cpp/build_cuda/tests/test_cuda_merkle_path[1]_tests.cmake")
else()
  add_test(test_cuda_merkle_path_NOT_BUILT test_cuda_merkle_path_NOT_BUILT)
endif()
