if(EXISTS "C:/Users/DELL/Desktop/WhirPlonk/cpp/build_cuda/tests/test_cuda_rs_sha256_merkle[1]_tests.cmake")
  include("C:/Users/DELL/Desktop/WhirPlonk/cpp/build_cuda/tests/test_cuda_rs_sha256_merkle[1]_tests.cmake")
else()
  add_test(test_cuda_rs_sha256_merkle_NOT_BUILT test_cuda_rs_sha256_merkle_NOT_BUILT)
endif()
